spring:
  datasource:
    url: jdbc:postgresql://localhost:5678/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
springdoc:
  swagger-ui:
    path: /swagger
